main: com.cavetale.halloween.HalloweenPlugin
name: Halloween

version: 0.1
api-version: 1.17

author: StarTux
description: Halloween Plugin 2021
website: https://github.com/StarTux/Halloween

depend: [Core, Mytems, Area, Resident, MagicMap]
softdepend: []

commands:

  hallow:
    aliases: []
    description: Player Click Command
    permission: halloween.player
    usage: ''

  halloween:
    aliases: []
    description: Admin Command
    permission: halloween.admin
    usage: |-
      /halloween

permissions:

  halloween.player:
    description: Play the games
    default: true

  halloween.admin:
    description: Use /halloween
    default: op

  halloween.nocooldown:
    description: Skip cooldowns
    default: false
